### ISSUE TITLE
rename / redefine the parameters for the healpix index

### ISSUE THREAD

**Issue by keewis** [xarray-contrib/xdggs#34]
We currently use `rot_latlon`, `nside`, and `nest` as grid parameters for healpix (mostly because those were inspired by `healpy`). However, I'd like to propose to a few changes:
- `nside`: `nside` describes the number of subdivisions per side, and is always a power of two. That means that by taking the base-2 logarithm of `nside` we get a new parameter with a definition that is much closer to the `resolution` of other DGGS. New names could be `order` (from `healpy`), `depth` (from `cdshealpix`), `level`, or indeed `resolution`.
- `nest`: In `healpy`, this is used to switch between the `nested` and `ring` indexing schemes. However, those are not the only ones in use, the [`unique`](https://emfollow.docs.ligo.org/userguide/tutorial/multiorder_skymaps.html#the-uniq-indexing-scheme) scheme also exists. As such, a boolean parameter does not seem to be a good idea. Instead, I'd use a string: `indexing_scheme="nested"`, `indexing_scheme="ring"`, or `indexing_scheme="unique"`.
- `rot_latlon`: I would call this just `rotation` (`proj` calls this [`rot_xy`](https://proj.org/en/9.3/operations/projections/healpix.html) to be consistent with the projections), where just like with `healpy` / `cdshealpix` the order would always be longitude then latitude. The values would still be specified as a list / 1D array. For example: `rotation=[0, 30]`.

What do you think?

**Comment by benbovy** [comment]
Those changes all make sense to me.

#35 would make it easier supporting both `nside` and `resolution` as inputs and validate the value.
