### ISSUE TITLE
renaming the primary grid parameter from `resolution` to `level`

### ISSUE THREAD

**Issue by keewis** [xarray-contrib/xdggs#64]
From #62:
> We've decided to go with `level` instead of resolution or `refinement_level` / `reflevel` etc. in the meeting, as the context is enough to disambiguate between other kinds of levels. In particular, "processing level" to me is a property of the data / dataset, not the grid (not sure what you're referring to with "maturity level", but if it has to do with the [data maturity](https://www.earthdata.nasa.gov/engage/open-data-services-and-software/data-and-information-policy/data-maturity-levels) I would also call that a property of the data or dataset, not the grid).

This issue is to track that change.

**Comment by strobpr** [comment]
Thanks, `level` is definitely better than resolution! A move in the right direction and when used in grid hierarchy context such as DGGS APIs, the term is not really ambiguous. I added a comment on the general wording to #65.

There are plenty of other 'levels' in EO and related geospatial sciences, I was referring to the levels of the [WGISS Data Management and Stewardship Maturity Matrix ](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://ceos.org/document_management/Working_Groups/WGISS/Interest_Groups/Data_Stewardship/White_Papers/WGISS%2520Data%2520Management%2520and%2520Stewardship%2520Maturity%2520Matrix.pdf&ved=2ahUKEwigrOSD6OGIAxXQzDgGHXbvAdEQFnoECBUQAQ&usg=AOvVaw0ngn4tleYqDcTa4k5zUjRi) just pointing at the fact that if the context is not crystal clear, speaking of 'data levels' might be interpretable.
