### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by keewis** [xarray-contrib/xdggs#76]
Any good library needs documentation. We got a readme in #70, but that's rarely enough.

**Comment by annefou** [comment]
For the API, how about using [sphinx-autoapi](https://github.com/readthedocs/sphinx-autoapi)?
We can then add installation instructions and a tutorial. How does that sound?

**Comment by annefou** [comment]
@keewis I started a draft PR for the doc. Happy to get feedback on the organisation, content, etc. https://github.com/xarray-contrib/xdggs/pull/80

**Comment by keewis** [comment]
thanks, I was about to open a PR for the API documentation. I'll try to get that in first, and we can then adapt whatever you have already.

**Comment by annefou** [comment]
Ok. I added autoapi. Maybe it is not good enough. It works locally.
